/**
 * ServiceAccountAuditService
 *
 * Manages audit logging for all service account operations.
 * Provides compliance trail and security monitoring.
 *
 * Features:
 * - Log all SA operations (create, update, delete, rotate, use)
 * - Store IP address, user agent, timestamp
 * - Query logs with filtering and pagination
 * - Immutable logs (RLS prevents user deletion)
 * - Automatic cleanup of old logs
 *
 * Logged Actions:
 * - create: Service account created
 * - update: Metadata updated (name, description, allowedUserIds, enabled)
 * - delete: Service account revoked/deleted
 * - rotate: Token rotated (new token generated)
 * - regenerate: Token regenerated (legacy support)
 * - use: Token used for API request
 */

import type { DbAdapter } from '../db/DbAdapter.js';

export type AuditAction = 'create' | 'update' | 'delete' | 'rotate' | 'regenerate' | 'use';

export interface AuditLogEntry {
  id?: string; // UUID (generated by database)
  serviceAccountId: string; // UUID of the service account
  userId: string; // Actor (email) who performed the action
  action: AuditAction; // Operation performed
  details?: Record<string, any>; // Action-specific metadata
  ipAddress?: string; // Request IP address
  userAgent?: string; // Request user agent
  success: boolean; // Whether the action succeeded
  errorMessage?: string; // Error message if action failed
  createdAt?: Date; // Timestamp (generated by database)
  authToken?: string; // JWT for RLS authentication
}

export interface AuditLogQueryOptions {
  limit?: number; // Max records to return (default: 50, max: 200)
  offset?: number; // Records to skip (for pagination)
  action?: AuditAction; // Filter by action type
  success?: boolean; // Filter by success status
  startDate?: Date; // Filter logs after this date
  endDate?: Date; // Filter logs before this date
}

export class ServiceAccountAuditService {
  constructor(private dbAdapter: DbAdapter) {
    console.log('[ServiceAccountAuditService] Audit service initialized');
  }

  /**
   * Log a service account operation
   *
   * Stores audit entry in database with RLS.
   * Logs are immutable (users cannot delete or modify).
   *
   * @param entry Audit log entry
   * @returns Promise that resolves when log is written
   *
   * @example
   * await auditService.log({
   *   serviceAccountId: 'uuid-xxx',
   *   userId: 'user@example.com',
   *   action: 'create',
   *   details: { name: 'CI/CD Pipeline', expiresIn: '90d' },
   *   ipAddress: '203.0.113.45',
   *   userAgent: 'curl/7.81.0',
   *   success: true
   * });
   */
  async log(entry: AuditLogEntry): Promise<void> {
    try {
      // Validate required fields
      if (!entry.serviceAccountId) {
        throw new Error('serviceAccountId is required');
      }
      if (!entry.userId) {
        throw new Error('userId is required');
      }
      if (!entry.action) {
        throw new Error('action is required');
      }

      // Insert into database using DbAdapter method
      await this.dbAdapter.createServiceAccountAuditLog(
        {
          serviceAccountId: entry.serviceAccountId,
          userId: entry.userId,
          action: entry.action,
          details: entry.details,
          ipAddress: entry.ipAddress,
          userAgent: entry.userAgent,
          success: entry.success,
          errorMessage: entry.errorMessage,
        },
        entry.authToken
      );

      console.log(
        `[ServiceAccountAuditService] Logged ${entry.action} by ${entry.userId} for SA ${entry.serviceAccountId} (${entry.success ? 'success' : 'failed'})`
      );
    } catch (error) {
      // Log error but don't throw - audit logging should not break main operation
      console.error('[ServiceAccountAuditService] Failed to log audit entry:', error);
      console.error('[ServiceAccountAuditService] Entry:', entry);
    }
  }

  /**
   * Get audit logs for a service account
   *
   * Returns paginated audit logs with optional filtering.
   * Only returns logs for SAs owned by the requesting user (RLS enforced).
   *
   * @param serviceAccountId UUID of the service account
   * @param userId Email of the requesting user (for RLS)
   * @param options Query options (pagination, filtering)
   * @returns Array of audit log entries
   *
   * @example
   * const logs = await auditService.getLogs('uuid-xxx', 'user@example.com', {
   *   limit: 50,
   *   offset: 0,
   *   action: 'use',
   *   success: true
   * });
   */
  async getLogs(
    serviceAccountId: string,
    userId: string,
    options: AuditLogQueryOptions = {},
    authToken?: string
  ): Promise<AuditLogEntry[]> {
    try {
      const { limit = 50, offset = 0, action, success, startDate, endDate } = options;

      // Validate limits
      if (limit < 1 || limit > 200) {
        throw new Error('Limit must be between 1 and 200');
      }
      if (offset < 0) {
        throw new Error('Offset must be non-negative');
      }

      // Query with DbAdapter method (supports limit, offset, action, success)
      const rawLogs = await this.dbAdapter.getServiceAccountAuditLogs(
        serviceAccountId,
        {
          limit,
          offset,
          action: action as any,
          success,
        },
        authToken
      );

      // Map to AuditLogEntry type (cast action to AuditAction)
      let logs: AuditLogEntry[] = rawLogs.map((log) => ({
        ...log,
        action: log.action as AuditAction,
      }));

      // Filter by date ranges if specified (client-side filtering)
      // Note: This is less efficient than database filtering, but works with current DbAdapter interface
      if (startDate || endDate) {
        logs = logs.filter((log) => {
          const logDate = log.createdAt;
          if (!logDate) return false; // Skip logs without timestamp
          if (startDate && logDate < startDate) return false;
          if (endDate && logDate > endDate) return false;
          return true;
        });
      }

      console.log(
        `[ServiceAccountAuditService] Retrieved ${logs.length} audit logs for SA ${serviceAccountId}`
      );

      return logs;
    } catch (error) {
      console.error('[ServiceAccountAuditService] Failed to get audit logs:', error);
      throw new Error('Failed to retrieve audit logs');
    }
  }

  /**
   * Get total count of audit logs (for pagination)
   *
   * @param serviceAccountId UUID of the service account
   * @param userId Email of the requesting user (for RLS)
   * @param options Query options (filtering only, no pagination)
   * @returns Total count of matching logs
   *
   * @example
   * const total = await auditService.getLogsCount('uuid-xxx', 'user@example.com', {
   *   action: 'use',
   *   success: true
   * });
   */
  async getLogsCount(
    serviceAccountId: string,
    userId: string,
    options: Omit<AuditLogQueryOptions, 'limit' | 'offset'> = {},
    authToken?: string
  ): Promise<number> {
    try {
      // Note: This is a simplified implementation using getLogs() with a large limit
      // A more efficient implementation would require a dedicated DbAdapter method
      const logs = await this.getLogs(
        serviceAccountId,
        userId,
        {
          ...options,
          limit: 10000, // Large limit to get all matching logs
          offset: 0,
        },
        authToken
      );

      return logs.length;
    } catch (error) {
      console.error('[ServiceAccountAuditService] Failed to get audit logs count:', error);
      return 0;
    }
  }

  /**
   * Cleanup old audit logs
   *
   * Deletes audit logs older than specified days.
   * Use for compliance with data retention policies.
   *
   * @param daysToKeep Number of days to keep logs
   * @returns Number of logs deleted
   *
   * @example
   * // Delete logs older than 365 days
   * const deleted = await auditService.cleanup(365);
   * console.log(`Deleted ${deleted} old audit logs`);
   */
  async cleanup(daysToKeep: number): Promise<number> {
    try {
      if (daysToKeep < 1) {
        throw new Error('daysToKeep must be at least 1');
      }

      // Note: Cleanup is not implemented as it requires a specialized DbAdapter method
      // This would need to be implemented directly at the database level or via a dedicated method
      console.warn(
        `[ServiceAccountAuditService] Cleanup operation not fully implemented - requires direct database access`
      );
      console.warn(
        `[ServiceAccountAuditService] To cleanup logs older than ${daysToKeep} days, use database-level operations`
      );

      return 0;
    } catch (error) {
      console.error('[ServiceAccountAuditService] Failed to cleanup audit logs:', error);
      throw new Error('Failed to cleanup audit logs');
    }
  }

  /**
   * Get usage statistics for a service account
   *
   * Returns aggregated usage metrics from audit logs.
   * Useful for monitoring and billing.
   *
   * @param serviceAccountId UUID of the service account
   * @param userId Email of the requesting user (for RLS)
   * @param days Number of days to analyze (default: 30)
   * @returns Usage statistics
   *
   * @example
   * const stats = await auditService.getUsageStats('uuid-xxx', 'user@example.com', 7);
   * // {
   * //   totalRequests: 1250,
   * //   successfulRequests: 1200,
   * //   failedRequests: 50,
   * //   uniqueDays: 7,
   * //   avgRequestsPerDay: 178.57
   * // }
   */
  async getUsageStats(
    serviceAccountId: string,
    userId: string,
    days: number = 30,
    authToken?: string
  ): Promise<{
    totalRequests: number;
    successfulRequests: number;
    failedRequests: number;
    uniqueDays: number;
    avgRequestsPerDay: number;
  }> {
    try {
      const startDate = new Date();
      startDate.setDate(startDate.getDate() - days);

      // Get all 'use' action logs for the date range
      const logs = await this.getLogs(
        serviceAccountId,
        userId,
        {
          limit: 10000,
          offset: 0,
          action: 'use',
          startDate,
        },
        authToken
      );

      // Calculate stats from logs
      const totalRequests = logs.length;
      const successfulRequests = logs.filter((log) => log.success).length;
      const failedRequests = logs.filter((log) => !log.success).length;

      // Calculate unique days
      const uniqueDaysSet = new Set<string>();
      logs.forEach((log) => {
        if (log.createdAt) {
          const dateStr = log.createdAt.toISOString().split('T')[0];
          uniqueDaysSet.add(dateStr);
        }
      });
      const uniqueDays = uniqueDaysSet.size || 1; // Avoid division by zero

      return {
        totalRequests,
        successfulRequests,
        failedRequests,
        uniqueDays,
        avgRequestsPerDay: totalRequests / uniqueDays,
      };
    } catch (error) {
      console.error('[ServiceAccountAuditService] Failed to get usage stats:', error);
      return {
        totalRequests: 0,
        successfulRequests: 0,
        failedRequests: 0,
        uniqueDays: 0,
        avgRequestsPerDay: 0,
      };
    }
  }
}
